### ISSUE TITLE
issue #8 Word Capitalization

### ISSUE THREAD

**Issue by binarybeast7** [binarybeast7/hots_below_1300#10]
Title - Word Capitalization
link - http://codeforces.com/problemset/problem/281/A

Capitalization is writing a word with its first letter as a capital letter. Your task is to capitalize the given word.

Note, that during capitalization all the letters except the first one remains unchanged.

Input
A single line contains a non-empty word. This word consists of lowercase and uppercase English letters. The length of the word will not exceed 103.

Output
Output the given word after capitalization.

Examples

input
ApPLe

output
ApPLe

input
konjac

output
Konjac

**Comment by war-18** [comment]
Can u assign this issue to me?
anujrw18
