### ISSUE TITLE
issue #4 Borze

### ISSUE THREAD

**Issue by binarybeast7** [binarybeast7/hots_below_1300#6]
title - Borze
link - http://codeforces.com/problemset/problem/32/B

Ternary numeric notation is quite popular in Berland. To telegraph the ternary number the Borze alphabet is used. Digit 0 is transmitted as «.», 1 as «-.» and 2 as «--». You are to decode the Borze code, i.e. to find out the ternary number given its representation in Borze alphabet.

Input
The first line contains a number in Borze code. The length of the string is between 1 and 200 characters. It's guaranteed that the given string is a valid Borze code of some ternary number (this number can have leading zeroes).

Output
Output the decoded ternary number. It can have leading zeroes.

Examples

input
.-.--
output
012

input
--.
output
20

input
-..-.--
output
1012

**Comment by dhirajpatil2346** [comment]
plz assign this to me

**Comment by dhirajpatil2346** [comment]
please assign this to me
